CREATE VIEW VW_RESUMO_TURMAS AS
SELECT 
  tp.NOM_PROFESSOR,
  tm.COD_ID_TURMA,
  td.NOM_DISCIPLINA,
  td.NUM_CARGA_HORARIA,
  ts.NUM_SALA,
  ts.NUM_CAPACIDADE,
  tt.NUM_SEMESTRE,
  tm.NUM_MATRICULA_ALUNO
FROM SAAI.TD_MATRICULA tm 
INNER JOIN SAAI.TD_TURMA tt ON tm.COD_ID_TURMA = tt.COD_ID_TURMA
INNER JOIN SAAI.TD_PROFESSOR tp ON tt.NUM_MATRICULA_PROFESSOR = tp.NUM_MATRICULA_PROFESSOR
INNER JOIN SAAI.TD_DISCIPLINA td ON tt.NUM_CODIGO_DISCIPLINA = td.NUM_CODIGO_DISCIPLINA
INNER JOIN SAAI.TD_SALA ts ON tt.NUM_SALA = ts.NUM_SALA;